name: Webhook Listener

on:
  repository_dispatch:
    types: [dockerhub_push]

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event
        run: echo "Webhook received from Docker Hub!"
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Latest Docker Image
        run: docker pull agorbach/far-2-cel:latest

      - name: Run Container in GitHub Runner
        run: |
          docker run -d -p 80:5000 --name flask-container agorbach/far-2-cel:latest

      - name: Check Running Containers
        run: docker ps
      - name: Install ngrok
        run: |
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/
          ngrok --version

      - name: Start ngrok tunnel
        run: |
          nohup ngrok http 8080 > /dev/null 2>&1 &
          sleep 5

      - name: Show ngrok URL
        run: |
          sleep 5
          curl -s http://localhost:4040/api/tunnels | grep -o '"public_url":"[^"]*' | cut -d'"' -f4
