name: Webhook Listener

on:
  repository_dispatch:
    types: [dockerhub_push]

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event
        run: echo "Webhook received from Docker Hub!"
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Latest Docker Image
        run: docker pull agorbach/far-2-cel:latest

      - name: Run Container in GitHub Runner
        run: |
          docker run -d -p 80:5000 --name flask-container agorbach/far-2-cel:latest

      - name: Check Running Containers
        run: docker ps
